.TH "C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts Directory Reference" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBenchmark01\&.cs\fP"
.br
.ti -1c
.RI "file \fBBenchmark01_UGUI\&.cs\fP"
.br
.ti -1c
.RI "file \fBBenchmark02\&.cs\fP"
.br
.ti -1c
.RI "file \fBBenchmark03\&.cs\fP"
.br
.ti -1c
.RI "file \fBBenchmark04\&.cs\fP"
.br
.ti -1c
.RI "file \fBCameraController\&.cs\fP"
.br
.ti -1c
.RI "file \fBChatController\&.cs\fP"
.br
.ti -1c
.RI "file \fBDropdownSample\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnvMapAnimator\&.cs\fP"
.br
.ti -1c
.RI "file \fBObjectSpin\&.cs\fP"
.br
.ti -1c
.RI "file \fBShaderPropAnimator\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleScript\&.cs\fP"
.br
.ti -1c
.RI "file \fBSkewTextExample\&.cs\fP"
.br
.ti -1c
.RI "file \fBTeleType\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextConsoleSimulator\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextMeshProFloatingText\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextMeshSpawner\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_DigitValidator\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_ExampleScript_01\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_FrameRateCounter\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_PhoneNumberValidator\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_TextEventCheck\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_TextEventHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_TextInfoDebugTool\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_TextSelector_A\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_TextSelector_B\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMP_UiFrameRateCounter\&.cs\fP"
.br
.ti -1c
.RI "file \fBTMPro_InstructionOverlay\&.cs\fP"
.br
.ti -1c
.RI "file \fBVertexColorCycler\&.cs\fP"
.br
.ti -1c
.RI "file \fBVertexJitter\&.cs\fP"
.br
.ti -1c
.RI "file \fBVertexShakeA\&.cs\fP"
.br
.ti -1c
.RI "file \fBVertexShakeB\&.cs\fP"
.br
.ti -1c
.RI "file \fBVertexZoom\&.cs\fP"
.br
.ti -1c
.RI "file \fBWarpTextExample\&.cs\fP"
.br
.in -1c
