.TH "C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/Scripts/GUIScripts Directory Reference" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/Scripts/GUIScripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGUISkewImage\&.cs\fP"
.br
.ti -1c
.RI "file \fBImageFillGradient\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainMenuManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBPauseMenuManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBStatisticManager\&.cs\fP"
.br
.in -1c
