.TH "ChatController" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChatController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TMP_InputField \fBTMP_ChatInput\fP"
.br
.ti -1c
.RI "TMP_Text \fBTMP_ChatOutput\fP"
.br
.ti -1c
.RI "Scrollbar \fBChatScrollbar\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Scrollbar ChatController\&.ChatScrollbar"

.SS "TMP_InputField ChatController\&.TMP_ChatInput"

.SS "TMP_Text ChatController\&.TMP_ChatOutput"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
