.TH "ChunkManager" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChunkManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject[] \fBchunkPrefabs\fP"
.br
.RI "Variables\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GameObject [] ChunkManager\&.chunkPrefabs"

.PP
Variables\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
