.TH "DropdownSample" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropdownSample
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnButtonClick\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void DropdownSample\&.OnButtonClick ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
