.TH "EnvMapAnimator" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvMapAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBRotationSpeeds\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Vector3 EnvMapAnimator\&.RotationSpeeds"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
