.TH "GameManager" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEndGame\fP ()"
.br
.RI "GAME: END\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBrestartDelay\fP = 1F"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void GameManager\&.EndGame ()"

.PP
GAME: END\&. End the game by Invoking a restart 
.SH "Member Data Documentation"
.PP 
.SS "float GameManager\&.restartDelay = 1F"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
