.TH "GUISkewImage" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUISkewImage
.SH SYNOPSIS
.br
.PP
.PP
Inherits Image\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPopulateMesh\fP (VertexHelper vh)"
.br
.RI "Allow an image to be skewed "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void GUISkewImage\&.OnPopulateMesh (VertexHelper vh)\fC [protected]\fP"

.PP
Allow an image to be skewed 

.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
