.TH "MainMenuManager" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenuManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOptionsMenu\fP ()"
.br
.RI "Trigger the options menu "
.ti -1c
.RI "void \fBQuitGame\fP ()"
.br
.RI "UI: Quit\&. "
.ti -1c
.RI "void \fBViewCredits\fP ()"
.br
.RI "UI: Credits\&. "
.ti -1c
.RI "void \fBReturnMain\fP ()"
.br
.RI "return to the main menu (from credits) "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Animator \fBoptions\fP"
.br
.RI "Animation Variables\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MainMenuManager\&.OptionsMenu ()"

.PP
Trigger the options menu 
.SS "void MainMenuManager\&.QuitGame ()"

.PP
UI: Quit\&. Quit the game 
.SS "void MainMenuManager\&.ReturnMain ()"

.PP
return to the main menu (from credits) 
.SS "void MainMenuManager\&.ViewCredits ()"

.PP
UI: Credits\&. View the credits menu 
.SH "Member Data Documentation"
.PP 
.SS "Animator MainMenuManager\&.options"

.PP
Animation Variables\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
