.TH "OscillateObstacle" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OscillateObstacle
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBrotationSpeed\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int OscillateObstacle\&.rotationSpeed = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
