.TH "ParrotThirdPersonCamera.ParrotThirdPersonCamera" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrotThirdPersonCamera.ParrotThirdPersonCamera
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBlookAt\fP"
.br
.ti -1c
.RI "Transform \fBcamTransform\fP"
.br
.ti -1c
.RI "float \fBdistance\fP = 5\&.0f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "Transform ParrotThirdPersonCamera\&.ParrotThirdPersonCamera\&.camTransform"

.SS "float ParrotThirdPersonCamera\&.ParrotThirdPersonCamera\&.distance = 5\&.0f"

.SS "Transform ParrotThirdPersonCamera\&.ParrotThirdPersonCamera\&.lookAt"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
