.TH "ParrotPlayer.ParrotPlayer" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrotPlayer.ParrotPlayer
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP = 600\&.0f"
.br
.ti -1c
.RI "float \fBturnSpeed\fP = 400\&.0f"
.br
.ti -1c
.RI "float \fBgravity\fP = 20\&.0f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float ParrotPlayer\&.ParrotPlayer\&.gravity = 20\&.0f"

.SS "float ParrotPlayer\&.ParrotPlayer\&.speed = 600\&.0f"

.SS "float ParrotPlayer\&.ParrotPlayer\&.turnSpeed = 400\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
