.TH "PlayerCollision" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerCollision
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetOrbCount\fP ()"
.br
.RI "GET ORB COUNT\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPlayerController\fP \fBmovement\fP"
.br
.ti -1c
.RI "AudioClip \fBdeathSound\fP"
.br
.ti -1c
.RI "int \fBflowerOrbs\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int PlayerCollision\&.GetOrbCount ()"

.PP
GET ORB COUNT\&. Return the current amount of orbs collected 
.SH "Member Data Documentation"
.PP 
.SS "AudioClip PlayerCollision\&.deathSound"

.SS "int PlayerCollision\&.flowerOrbs"

.SS "\fBPlayerController\fP PlayerCollision\&.movement"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
