.TH "PlayerShatter" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerShatter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshatter\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBcubeSize\fP = 0\&.2f"
.br
.RI "Variables\&. "
.ti -1c
.RI "int \fBcubesInRow\fP = 5"
.br
.ti -1c
.RI "float \fBshatterForce\fP = 50f"
.br
.ti -1c
.RI "float \fBshatterRadius\fP = 4f"
.br
.ti -1c
.RI "float \fBshatterUpward\fP = 0\&.4f"
.br
.ti -1c
.RI "Material \fBmatPlayer\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void PlayerShatter\&.shatter ()"

.PP
SHATTER Function Create player shattering effect 
.SH "Member Data Documentation"
.PP 
.SS "int PlayerShatter\&.cubesInRow = 5"

.SS "float PlayerShatter\&.cubeSize = 0\&.2f"

.PP
Variables\&. 
.SS "Material PlayerShatter\&.matPlayer"

.SS "float PlayerShatter\&.shatterForce = 50f"

.SS "float PlayerShatter\&.shatterRadius = 4f"

.SS "float PlayerShatter\&.shatterUpward = 0\&.4f"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
