.TH "StatisticManager" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBplayer\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBscoreText\fP"
.br
.RI "Score Variables\&. "
.ti -1c
.RI "TextMeshProUGUI \fBdistanceText\fP"
.br
.RI "Distance Variables\&. "
.ti -1c
.RI "TextMeshProUGUI \fBcollectiblesText\fP"
.br
.RI "Collectible Variables\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void StatisticManager\&.Awake ()"

.SH "Member Data Documentation"
.PP 
.SS "TextMeshProUGUI StatisticManager\&.collectiblesText"

.PP
Collectible Variables\&. 
.SS "TextMeshProUGUI StatisticManager\&.distanceText"

.PP
Distance Variables\&. 
.SS "Transform StatisticManager\&.player"

.SS "TextMeshProUGUI StatisticManager\&.scoreText"

.PP
Score Variables\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
