.TH "C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_TextEventHandler.cs" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_TextEventHandler.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\&.CharacterSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\&.SpriteSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\&.WordSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\&.LineSelectionEvent\fP"
.br
.ti -1c
.RI "class \fBTMPro\&.TMP_TextEventHandler\&.LinkSelectionEvent\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMPro\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
