.TH "C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_DigitValidator.cs" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thebe/Documents/GitHub/7-CrossPlatformDev/TenProznia/Assets/TextMesh Pro/Examples & Extras/Scripts/TMP_DigitValidator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMPro\&.TMP_DigitValidator\fP"
.br
.RI "EXample of a Custom Character Input Validator to only allow digits from 0 to 9\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTMPro\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
