.TH "TMPro.Examples.TMP_FrameRateCounter" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMP_FrameRateCounter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFpsCounterAnchorPositions\fP { \fBTopLeft\fP, \fBBottomLeft\fP, \fBTopRight\fP, \fBBottomRight\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBUpdateInterval\fP = 5\&.0f"
.br
.ti -1c
.RI "\fBFpsCounterAnchorPositions\fP \fBAnchorPosition\fP = \fBFpsCounterAnchorPositions\&.TopRight\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.Examples\&.TMP_FrameRateCounter\&.FpsCounterAnchorPositions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITopLeft \fP\fP
.TP
\fB\fIBottomLeft \fP\fP
.TP
\fB\fITopRight \fP\fP
.TP
\fB\fIBottomRight \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBFpsCounterAnchorPositions\fP TMPro\&.Examples\&.TMP_FrameRateCounter\&.AnchorPosition = \fBFpsCounterAnchorPositions\&.TopRight\fP"

.SS "float TMPro\&.Examples\&.TMP_FrameRateCounter\&.UpdateInterval = 5\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
