.TH "TMPro.Examples.CameraController" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.CameraController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBCameraModes\fP { \fBFollow\fP, \fBIsometric\fP, \fBFree\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBCameraTarget\fP"
.br
.ti -1c
.RI "float \fBFollowDistance\fP = 30\&.0f"
.br
.ti -1c
.RI "float \fBMaxFollowDistance\fP = 100\&.0f"
.br
.ti -1c
.RI "float \fBMinFollowDistance\fP = 2\&.0f"
.br
.ti -1c
.RI "float \fBElevationAngle\fP = 30\&.0f"
.br
.ti -1c
.RI "float \fBMaxElevationAngle\fP = 85\&.0f"
.br
.ti -1c
.RI "float \fBMinElevationAngle\fP = 0f"
.br
.ti -1c
.RI "float \fBOrbitalAngle\fP = 0f"
.br
.ti -1c
.RI "\fBCameraModes\fP \fBCameraMode\fP = \fBCameraModes\&.Follow\fP"
.br
.ti -1c
.RI "bool \fBMovementSmoothing\fP = true"
.br
.ti -1c
.RI "bool \fBRotationSmoothing\fP = false"
.br
.ti -1c
.RI "float \fBMovementSmoothingValue\fP = 25f"
.br
.ti -1c
.RI "float \fBRotationSmoothingValue\fP = 5\&.0f"
.br
.ti -1c
.RI "float \fBMoveSensitivity\fP = 2\&.0f"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.Examples\&.CameraController\&.CameraModes\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFollow \fP\fP
.TP
\fB\fIIsometric \fP\fP
.TP
\fB\fIFree \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBCameraModes\fP TMPro\&.Examples\&.CameraController\&.CameraMode = \fBCameraModes\&.Follow\fP"

.SS "Transform TMPro\&.Examples\&.CameraController\&.CameraTarget"

.SS "float TMPro\&.Examples\&.CameraController\&.ElevationAngle = 30\&.0f"

.SS "float TMPro\&.Examples\&.CameraController\&.FollowDistance = 30\&.0f"

.SS "float TMPro\&.Examples\&.CameraController\&.MaxElevationAngle = 85\&.0f"

.SS "float TMPro\&.Examples\&.CameraController\&.MaxFollowDistance = 100\&.0f"

.SS "float TMPro\&.Examples\&.CameraController\&.MinElevationAngle = 0f"

.SS "float TMPro\&.Examples\&.CameraController\&.MinFollowDistance = 2\&.0f"

.SS "bool TMPro\&.Examples\&.CameraController\&.MovementSmoothing = true"

.SS "float TMPro\&.Examples\&.CameraController\&.MovementSmoothingValue = 25f"

.SS "float TMPro\&.Examples\&.CameraController\&.MoveSensitivity = 2\&.0f"

.SS "float TMPro\&.Examples\&.CameraController\&.OrbitalAngle = 0f"

.SS "bool TMPro\&.Examples\&.CameraController\&.RotationSmoothing = false"

.SS "float TMPro\&.Examples\&.CameraController\&.RotationSmoothingValue = 5\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
