.TH "TMPro.Examples.TMP_TextSelector_A" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMP_TextSelector_A
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void TMPro\&.Examples\&.TMP_TextSelector_A\&.OnPointerEnter (PointerEventData eventData)"

.SS "void TMPro\&.Examples\&.TMP_TextSelector_A\&.OnPointerExit (PointerEventData eventData)"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
