.TH "TMPro.Examples.ObjectSpin" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.ObjectSpin
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMotionType\fP { \fBRotation\fP, \fBBackAndForth\fP, \fBTranslation\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBSpinSpeed\fP = 5"
.br
.ti -1c
.RI "int \fBRotationRange\fP = 15"
.br
.ti -1c
.RI "\fBMotionType\fP \fBMotion\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.Examples\&.ObjectSpin\&.MotionType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRotation \fP\fP
.TP
\fB\fIBackAndForth \fP\fP
.TP
\fB\fITranslation \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBMotionType\fP TMPro\&.Examples\&.ObjectSpin\&.Motion"

.SS "int TMPro\&.Examples\&.ObjectSpin\&.RotationRange = 15"

.SS "float TMPro\&.Examples\&.ObjectSpin\&.SpinSpeed = 5"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
