.TH "TMPro.TMP_TextEventHandler.WordSelectionEvent" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_TextEventHandler.WordSelectionEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEvent< string, int, int >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
