.TH "TMPro.Examples.Benchmark02" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.Benchmark02
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBSpawnType\fP = 0"
.br
.ti -1c
.RI "int \fBNumberOfNPC\fP = 12"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.Examples\&.Benchmark02\&.NumberOfNPC = 12"

.SS "int TMPro\&.Examples\&.Benchmark02\&.SpawnType = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
