.TH "TMPro.Examples.TextMeshProFloatingText" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TextMeshProFloatingText
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fBDisplayTextMeshProFloatingText\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBDisplayTextMeshFloatingText\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Font \fBTheFont\fP"
.br
.ti -1c
.RI "int \fBSpawnType\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator TMPro\&.Examples\&.TextMeshProFloatingText\&.DisplayTextMeshFloatingText ()"

.SS "IEnumerator TMPro\&.Examples\&.TextMeshProFloatingText\&.DisplayTextMeshProFloatingText ()"

.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.Examples\&.TextMeshProFloatingText\&.SpawnType"

.SS "Font TMPro\&.Examples\&.TextMeshProFloatingText\&.TheFont"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
