.TH "TMPro" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBExamples\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTMP_DigitValidator\fP"
.br
.RI "EXample of a Custom Character Input Validator to only allow digits from 0 to 9\&. "
.ti -1c
.RI "class \fBTMP_PhoneNumberValidator\fP"
.br
.RI "Example of a Custom Character Input Validator to only allow phone number in the (800) 555-1212 format\&. "
.ti -1c
.RI "class \fBTMP_TextEventHandler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
