.TH "TMPro.Examples.TMP_ExampleScript_01" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.TMP_ExampleScript_01
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBobjectType\fP { \fBTextMeshPro\fP = 0, \fBTextMeshProUGUI\fP = 1 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBobjectType\fP \fBObjectType\fP"
.br
.ti -1c
.RI "bool \fBisStatic\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.Examples\&.TMP_ExampleScript_01\&.objectType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITextMeshPro \fP\fP
.TP
\fB\fITextMeshProUGUI \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "bool TMPro\&.Examples\&.TMP_ExampleScript_01\&.isStatic"

.SS "\fBobjectType\fP TMPro\&.Examples\&.TMP_ExampleScript_01\&.ObjectType"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
