.TH "TMPro.Examples.Benchmark03" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.Benchmark03
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBenchmarkType\fP { \fBTMP_SDF_MOBILE\fP = 0, \fBTMP_SDF__MOBILE_SSD\fP = 1, \fBTMP_SDF\fP = 2, \fBTMP_BITMAP_MOBILE\fP = 3, \fBTEXTMESH_BITMAP\fP = 4 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNumberOfSamples\fP = 100"
.br
.ti -1c
.RI "\fBBenchmarkType\fP \fBBenchmark\fP"
.br
.ti -1c
.RI "Font \fBSourceFontFile\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTMPro\&.Examples\&.Benchmark03\&.BenchmarkType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITMP_SDF_MOBILE \fP\fP
.TP
\fB\fITMP_SDF__MOBILE_SSD \fP\fP
.TP
\fB\fITMP_SDF \fP\fP
.TP
\fB\fITMP_BITMAP_MOBILE \fP\fP
.TP
\fB\fITEXTMESH_BITMAP \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "\fBBenchmarkType\fP TMPro\&.Examples\&.Benchmark03\&.Benchmark"

.SS "int TMPro\&.Examples\&.Benchmark03\&.NumberOfSamples = 100"

.SS "Font TMPro\&.Examples\&.Benchmark03\&.SourceFontFile"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
