.TH "TMPro.Examples.VertexShakeA" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.VertexShakeA
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBAngleMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBSpeedMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBScaleMultiplier\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBRotationMultiplier\fP = 1\&.0f"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float TMPro\&.Examples\&.VertexShakeA\&.AngleMultiplier = 1\&.0f"

.SS "float TMPro\&.Examples\&.VertexShakeA\&.RotationMultiplier = 1\&.0f"

.SS "float TMPro\&.Examples\&.VertexShakeA\&.ScaleMultiplier = 1\&.0f"

.SS "float TMPro\&.Examples\&.VertexShakeA\&.SpeedMultiplier = 1\&.0f"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
