.TH "TMPro.Examples.Benchmark04" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.Benchmark04
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBSpawnType\fP = 0"
.br
.ti -1c
.RI "int \fBMinPointSize\fP = 12"
.br
.ti -1c
.RI "int \fBMaxPointSize\fP = 64"
.br
.ti -1c
.RI "int \fBSteps\fP = 4"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.Examples\&.Benchmark04\&.MaxPointSize = 64"

.SS "int TMPro\&.Examples\&.Benchmark04\&.MinPointSize = 12"

.SS "int TMPro\&.Examples\&.Benchmark04\&.SpawnType = 0"

.SS "int TMPro\&.Examples\&.Benchmark04\&.Steps = 4"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
