.TH "TMPro.TMP_PhoneNumberValidator" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.TMP_PhoneNumberValidator \- Example of a Custom Character Input Validator to only allow phone number in the (800) 555-1212 format\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits TMP_InputValidator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override char \fBValidate\fP (ref string text, ref int pos, char ch)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Example of a Custom Character Input Validator to only allow phone number in the (800) 555-1212 format\&. 
.SH "Member Function Documentation"
.PP 
.SS "override char TMPro\&.TMP_PhoneNumberValidator\&.Validate (ref string text, ref int pos, char ch)"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
