.TH "TMPro.Examples.Benchmark01_UGUI" 3 "Fri Sep 24 2021" "Version v1" "TenProznia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TMPro.Examples.Benchmark01_UGUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBBenchmarkType\fP = 0"
.br
.ti -1c
.RI "Canvas \fBcanvas\fP"
.br
.ti -1c
.RI "TMP_FontAsset \fBTMProFont\fP"
.br
.ti -1c
.RI "Font \fBTextMeshFont\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int TMPro\&.Examples\&.Benchmark01_UGUI\&.BenchmarkType = 0"

.SS "Canvas TMPro\&.Examples\&.Benchmark01_UGUI\&.canvas"

.SS "Font TMPro\&.Examples\&.Benchmark01_UGUI\&.TextMeshFont"

.SS "TMP_FontAsset TMPro\&.Examples\&.Benchmark01_UGUI\&.TMProFont"


.SH "Author"
.PP 
Generated automatically by Doxygen for TenProznia from the source code\&.
